version: '3.8'

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psy-agents-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - psy-agents-network
    command: python -m psy_agents_noaug.cli --help

  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: psy-agents-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlruns
    networks:
      - psy-agents-network
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Test runner
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: psy-agents-test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - psy-agents-network
    command: poetry run pytest tests/ -v
    profiles:
      - test

networks:
  psy-agents-network:
    driver: bridge

volumes:
  mlflow-data:
  app-data:
