defaults:
  - _self_

project: joint

dataset:
  path: data/processed/redsm5_matched_evidence.csv
  sentence_column: sentence_text
  context_column: post_text
  label_column: status
  criteria_max_length: 256
  evidence_max_length: 512
  num_workers: 4

model:
  criteria_model: bert-base-uncased
  evidence_model: bert-base-uncased
  criteria:
    dropout: 0.1
    layer_num: 1
    hidden_dims: []
  evidence:
    dropout: 0.1
  fusion:
    dropout: 0.1

training:
  epochs: 3
  learning_rate: 2e-5
  train_batch_size: 8
  eval_batch_size: 16
  gradient_accumulation: 1
  max_grad_norm: 1.0
  logging_steps: 50
  seed: 42
  loss_weights:
    criteria: 1.0
    evidence: 1.0
  optimizer:
    name: adamw
    weight_decay: 0.01
  scheduler:
    name: linear
    warmup_steps: 0
  monitor_metric: validation_joint_score
  monitor_mode: max

mlflow:
  tracking_uri: sqlite:///mlflow.db
  experiment: Joint
  artifact_location: null
  tags:
    project: joint

optuna:
  storage: sqlite:///optuna.db
  study_name: joint_hpo
  direction: maximize

hydra:
  run:
    dir: outputs/joint/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/joint/multirun
    subdir: ${hydra.job.num}
## Training overrides for Joint architecture
#
# Compose with model/task configs to adjust epochs, batch sizes and runtime
# settings for training joint criteria+evidence models.
