version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_URI=file:///workspace/mlruns
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: sleep infinity
    networks:
      - psy-network

  mlflow:
    image: python:3.10-slim
    working_dir: /
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../mlruns:/mlruns
      - ../mlflow.db:/mlflow.db
    command: >
      bash -c "pip install --no-cache-dir mlflow &&
               mlflow ui --host 0.0.0.0 --port 5000
               --backend-store-uri sqlite:////mlflow.db
               --default-artifact-root file:///mlruns"
    ports:
      - "5000:5000"
    networks:
      - psy-network

networks:
  psy-network:
    driver: bridge
