# Training defaults for NO-AUG pipeline

num_epochs: 100
batch_size: 16
eval_batch_size: 32
learning_rate: 2.0e-5
weight_decay: 0.01
max_length: 512
gradient_clip: 1.0
gradient_accumulation_steps: 1

scheduler:
  type: "cosine"
  warmup_ratio: 0.06

optimizer:
  name: "adamw"
  betas: [0.9, 0.999]
  eps: 1.0e-8

amp:
  enabled: true
  dtype: "float16"

early_stopping:
  metric: "val_f1_macro"
  mode: "max"
  patience: 20
  min_delta: 0.0001

logging_steps: 100
eval_steps: 500

# DataLoader Optimization (2025 best practices)
num_workers: 8  # Start with 2x CPU cores per GPU
pin_memory: true  # Always true for GPU training
persistent_workers: true  # Keep workers alive between epochs
prefetch_factor: 2  # Batches prefetched per worker

# Reproducibility
deterministic: true  # Full reproducibility
cudnn_benchmark: false  # Deterministic algorithm selection

# Device
device: "cuda"
