optuna:
  storage: sqlite:///optuna.db
  study_name: evidence_hpo
  direction: maximize
  n_trials: 30
  timeout: null
  sampler: tpe
  pruner: median

search_space:
  training.train_batch_size:
    distribution: categorical
    choices: [4, 8, 16]
  training.eval_batch_size:
    distribution: categorical
    choices: [8, 16, 32]
  training.learning_rate:
    distribution: loguniform
    low: 1.0e-6
    high: 5.0e-4
  training.optimizer.name:
    distribution: categorical
    choices: [adamw, adam, adafactor]
  training.optimizer.weight_decay:
    distribution: loguniform
    low: 1.0e-6
    high: 1.0e-1
  training.scheduler.name:
    distribution: categorical
    choices: [linear, cosine, cosine_with_restarts, none]
  training.scheduler.warmup_steps:
    distribution: int
    low: 0
    high: 1000
  model.dropout:
    distribution: uniform
    low: 0.05
    high: 0.3
  dataset.max_length:
    distribution: categorical
    choices: [384, 448, 512]
