# Stage 2: Fine-grained search around best parameters

stage: 2
stage_name: "fine_search"
description: "Narrow search around best parameters from stage 1"

# Optuna settings
n_trials: 24
timeout: null
direction: "maximize"  # Maximize validation F1 macro
metric: "val_f1_macro"

# Training overrides
num_epochs: 10

# Narrowed search space (refine after stage 1)
search_space:
  learning_rate:
    type: "loguniform"
    low: 5.0e-6
    high: 1.0e-5

  weight_decay:
    type: "loguniform"
    low: 5.0e-4
    high: 5.0e-2

  warmup_ratio:
    type: "uniform"
    low: 0.05
    high: 0.15

  dropout:
    type: "uniform"
    low: 0.05
    high: 0.20

  batch_size:
    type: "categorical"
    choices: [16, 32]

  max_length:
    type: "categorical"
    choices: [384, 512]

  gradient_clip:
    type: "uniform"
    low: 0.5
    high: 2.0

# Use best encoder from stage 1
use_best_encoder: true

# Sampler
sampler:
  type: "tpe"
  n_startup_trials: 6
  multivariate: true
  group: true

# Pruner
pruner:
  type: "hyperband"
  min_resource: 2
  max_resource: 10
  reduction_factor: 3
## HPO Stage 2 — Fine search
#
# Narrows around the best configs from stage 1 with more training steps/epochs.
