# Stage 0: Sanity check with minimal trials

stage: 0
stage_name: "sanity_check"
description: "Quick sanity check with default hyperparameters"

# Optuna settings
n_trials: 8
timeout: null
direction: "maximize"  # Maximize validation F1 macro
metric: "val_f1_macro"

# Training overrides for sanity check
num_epochs: 3

# Search space (wide bounds for sanity check)
search_space:
  learning_rate:
    type: "loguniform"
    low: 1.0e-6
    high: 5.0e-5
  
  weight_decay:
    type: "loguniform"
    low: 1.0e-5
    high: 1.0e-1
  
  batch_size:
    type: "categorical"
    choices: [8, 16, 32]
  
  warmup_ratio:
    type: "uniform"
    low: 0.0
    high: 0.2
  
  dropout:
    type: "uniform"
    low: 0.0
    high: 0.3

# Sampler
sampler:
  type: "tpe"
  n_startup_trials: 3

# Pruner
pruner:
  type: "median"
  n_startup_trials: 2
  n_warmup_steps: 1
