name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1

    - name: Install dependencies
      run: poetry install --no-interaction --with dev

    - name: Run ruff
      run: poetry run ruff check src/ tests/ scripts/

    - name: Check black formatting
      run: poetry run black --check src/ tests/ scripts/

    - name: Check isort
      run: poetry run isort --check-only src/ tests/ scripts/

    - name: Run bandit security check
      run: poetry run bandit -r src/ -f json -o bandit-report.json || true

    - name: Upload bandit report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: bandit-security-report
        path: bandit-report.json

  type-check:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Check for TODO comments
      run: |
        echo "Checking for TODO comments..."
        grep -r "TODO" src/ || echo "No TODOs found"
